import { BlockCatalogSource } from './block-catalog';

/** Small development fixture only; it is not a vanilla block list. */
export const representativeBlockFixture: BlockCatalogSource = {
  minecraftVersion: '1.21.1',
  blocks: [
    { id: 'minecraft:stone', displayName: 'Stone', defaultState: {}, stateDefinitions: [], resources: { model: 'minecraft:block/stone', textures: ['minecraft:block/stone'] }, support: 'full', behavior: { kind: 'solid' } },
    { id: 'minecraft:stone_slab', displayName: 'Stone Slab', defaultState: { type: 'bottom', waterlogged: 'false' }, stateDefinitions: [{ name: 'type', values: ['bottom', 'top', 'double'] }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/stone_slab.json', textures: ['minecraft:block/stone'] }, support: 'full' },
    { id: 'minecraft:white_carpet', displayName: 'White Carpet', defaultState: {}, stateDefinitions: [], resources: { blockstate: 'minecraft:blockstates/white_carpet.json', textures: ['minecraft:block/white_wool'] }, support: 'full' },
    { id: 'minecraft:chain', displayName: 'Chain', defaultState: { axis: 'y', waterlogged: 'false' }, stateDefinitions: [{ name: 'axis', values: ['x', 'y', 'z'] }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/chain.json', textures: ['minecraft:block/chain'] }, support: 'partial', behavior: { kind: 'vertical-chain', axisProperty: 'axis', verticalAxis: 'y' } },
    { id: 'minecraft:lantern', displayName: 'Lantern', defaultState: { hanging: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'hanging', values: ['true', 'false'] }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/lantern.json', textures: ['minecraft:block/lantern'] }, support: 'full', behavior: { kind: 'lantern-placement', hangingProperty: 'hanging', chainId: 'minecraft:chain' } },
    { id: 'minecraft:dandelion', displayName: 'Dandelion', defaultState: {}, stateDefinitions: [], resources: { blockstate: 'minecraft:blockstates/dandelion.json', textures: ['minecraft:block/dandelion'] }, support: 'partial', behavior: { kind: 'floor-supported' } },
    { id: 'minecraft:oak_trapdoor', displayName: 'Oak Trapdoor', defaultState: { facing: 'north', half: 'bottom', open: 'false', powered: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }, { name: 'half', values: ['bottom', 'top'] }, { name: 'open', values: ['true', 'false'] }, { name: 'powered', values: ['true', 'false'] }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/oak_trapdoor.json', textures: ['minecraft:block/oak_trapdoor'] }, support: 'full' },
    { id: 'minecraft:oak_log', displayName: 'Oak Log', defaultState: { axis: 'y' }, stateDefinitions: [{ name: 'axis', values: ['x', 'y', 'z'] }], resources: { blockstate: 'minecraft:blockstates/oak_log.json', textures: ['minecraft:block/oak_log', 'minecraft:block/oak_log_top'] }, support: 'full' },
    { id: 'minecraft:oak_stairs', displayName: 'Oak Stairs', defaultState: { facing: 'north', half: 'bottom', shape: 'straight', waterlogged: 'false' }, stateDefinitions: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }, { name: 'half', values: ['top', 'bottom'] }, { name: 'shape', values: ['straight', 'inner_left', 'inner_right', 'outer_left', 'outer_right'], derived: true }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/oak_stairs.json', model: 'minecraft:block/oak_stairs', textures: ['minecraft:block/oak_planks'] }, support: 'full', behavior: { kind: 'stairs', derivedProperties: ['shape'] } },
    { id: 'minecraft:oak_fence', displayName: 'Oak Fence', defaultState: { north: 'false', east: 'false', south: 'false', west: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['true', 'false'], derived: true }, { name: 'east', values: ['true', 'false'], derived: true }, { name: 'south', values: ['true', 'false'], derived: true }, { name: 'west', values: ['true', 'false'], derived: true }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/oak_fence.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'fence', connectionGroup: 'wood-fence', compatibleGroups: ['wood-fence'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west'] } },
    { id: 'minecraft:spruce_fence', displayName: 'Spruce Fence', defaultState: { north: 'false', east: 'false', south: 'false', west: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['true', 'false'], derived: true }, { name: 'east', values: ['true', 'false'], derived: true }, { name: 'south', values: ['true', 'false'], derived: true }, { name: 'west', values: ['true', 'false'], derived: true }], resources: { blockstate: 'minecraft:blockstates/spruce_fence.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'fence', connectionGroup: 'wood-fence', compatibleGroups: ['wood-fence'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west'] } },
    { id: 'minecraft:nether_brick_fence', displayName: 'Nether Brick Fence', defaultState: { north: 'false', east: 'false', south: 'false', west: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['true', 'false'], derived: true }, { name: 'east', values: ['true', 'false'], derived: true }, { name: 'south', values: ['true', 'false'], derived: true }, { name: 'west', values: ['true', 'false'], derived: true }], resources: { blockstate: 'minecraft:blockstates/nether_brick_fence.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'fence', connectionGroup: 'nether-fence', compatibleGroups: ['nether-fence'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west'] } },
    { id: 'minecraft:cobblestone_wall', displayName: 'Cobblestone Wall', defaultState: { north: 'none', east: 'none', south: 'none', west: 'none', up: 'true', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['none', 'low', 'tall'], derived: true }, { name: 'east', values: ['none', 'low', 'tall'], derived: true }, { name: 'south', values: ['none', 'low', 'tall'], derived: true }, { name: 'west', values: ['none', 'low', 'tall'], derived: true }, { name: 'up', values: ['true', 'false'], derived: true }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/cobblestone_wall.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'wall', connectionGroup: 'wall', compatibleGroups: ['wall'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west', 'up'] } },
    { id: 'minecraft:glass_pane', displayName: 'Glass Pane', defaultState: { north: 'false', east: 'false', south: 'false', west: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['true', 'false'], derived: true }, { name: 'east', values: ['true', 'false'], derived: true }, { name: 'south', values: ['true', 'false'], derived: true }, { name: 'west', values: ['true', 'false'], derived: true }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/glass_pane.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'pane', connectionGroup: 'pane', compatibleGroups: ['pane'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west'] } },
    { id: 'minecraft:iron_bars', displayName: 'Iron Bars', defaultState: { north: 'false', east: 'false', south: 'false', west: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'north', values: ['true', 'false'], derived: true }, { name: 'east', values: ['true', 'false'], derived: true }, { name: 'south', values: ['true', 'false'], derived: true }, { name: 'west', values: ['true', 'false'], derived: true }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/iron_bars.json', textures: [] }, support: 'full', behavior: { kind: 'horizontal-connect', family: 'pane', connectionGroup: 'pane', compatibleGroups: ['pane'], connectsToSolid: true, derivedProperties: ['north', 'east', 'south', 'west'] } },
    { id: 'minecraft:torch', displayName: 'Torch', defaultState: {}, stateDefinitions: [], resources: { blockstate: 'minecraft:blockstates/torch.json', textures: [] }, support: 'full', behavior: { kind: 'torch-placement', wallBlockId: 'minecraft:wall_torch' } },
    { id: 'minecraft:white_candle', displayName: 'White Candle', defaultState: { candles: '1', lit: 'false', waterlogged: 'false' }, stateDefinitions: [{ name: 'candles', values: ['1', '2', '3', '4'] }, { name: 'lit', values: ['true', 'false'] }, { name: 'waterlogged', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/white_candle.json', textures: [] }, support: 'full', behavior: { kind: 'candle', candlesProperty: 'candles', maxCandles: 4 } },
    { id: 'minecraft:wall_torch', displayName: 'Wall Torch', defaultState: { facing: 'north' }, stateDefinitions: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }], resources: { blockstate: 'minecraft:blockstates/wall_torch.json', textures: [] }, support: 'partial', behavior: { kind: 'wall-mounted', facingProperty: 'facing' } },
    { id: 'minecraft:oak_door', displayName: 'Oak Door', defaultState: { facing: 'north', half: 'lower', hinge: 'left', open: 'false', powered: 'false' }, stateDefinitions: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }, { name: 'half', values: ['lower', 'upper'], derived: true }, { name: 'hinge', values: ['left', 'right'] }, { name: 'open', values: ['true', 'false'] }, { name: 'powered', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/oak_door.json', textures: [] }, support: 'partial', behavior: { kind: 'double-height', halfProperty: 'half', requiresFloor: true } },
    { id: 'minecraft:sunflower', displayName: 'Sunflower', defaultState: { half: 'lower' }, stateDefinitions: [{ name: 'half', values: ['lower', 'upper'], derived: true }], resources: { blockstate: 'minecraft:blockstates/sunflower.json', textures: [] }, support: 'partial', behavior: { kind: 'double-height', halfProperty: 'half', requiresFloor: true } },
    { id: 'minecraft:red_bed', displayName: 'Red Bed', defaultState: { facing: 'north', part: 'foot', occupied: 'false' }, stateDefinitions: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }, { name: 'part', values: ['foot', 'head'], derived: true }, { name: 'occupied', values: ['true', 'false'] }], resources: { blockstate: 'minecraft:blockstates/red_bed.json', textures: [] }, support: 'full', behavior: { kind: 'paired-horizontal', partProperty: 'part', facingProperty: 'facing', firstPart: 'foot', secondPart: 'head' } },
    { id: 'example:missing_renderer', displayName: 'Example Missing Renderer', defaultState: {}, stateDefinitions: [], resources: { textures: [] }, support: 'fallback', modName: 'Example Mod' },
  ],
};
