import type { RendererCounters } from '../engine/renderer-diagnostics';
import type { ViewportPerformanceEvidence } from './viewport-diagnostics-contracts';
import type { SceneRenderCost } from './scene-render-cost';
import type { ChunkSurfaceRenderer } from '../terrain/chunk-surface-renderer';
import type { StaticModelBatchRenderer } from '../batching/static-model-batch-renderer';
import type { FluidRenderCoordinator } from '../fluids/fluid-render-coordinator';

export interface ViewportPerformanceEvidencePort {
  readonly counters: RendererCounters;
  readonly terrain: ReturnType<ChunkSurfaceRenderer['evidence']>;
  readonly renderCost: SceneRenderCost;
  readonly staticModelMetrics: ReturnType<StaticModelBatchRenderer['metrics']>;
  readonly fluidDiagnostics: ReturnType<FluidRenderCoordinator['diagnostics']>;
  readonly lastRendererMetrics: { readonly calls: number; readonly triangles: number; readonly geometries: number; readonly textures: number; readonly lines: number; readonly points: number };
  readonly renderedBlocks: number;
  readonly renderedDecorations: number;
  readonly renderRegionSize: number;
  readonly instanceBatchCount: number;
  readonly surfaceFaceBatchCount: number;
  readonly hydrationQueue: number;
  readonly hydrationRunning: number;
  readonly interiorBlocksCulled: number;
  readonly frameDurationMs: number;
  readonly renderCpuMs: number;
  readonly spatialIndexLookups: number;
  readonly terrainAtlasMode: ViewportPerformanceEvidence['terrainAtlasMode'];
}
export function collectPerformanceEvidence(port: ViewportPerformanceEvidencePort): ViewportPerformanceEvidence {
    const counters = port.counters;
    const terrain = port.terrain;
    const renderCost = port.renderCost;
    const staticModelMetrics = port.staticModelMetrics;
    return {
      renderCalls: port.lastRendererMetrics.calls,
      triangles: port.lastRendererMetrics.triangles,
      geometries: port.lastRendererMetrics.geometries,
      textures: port.lastRendererMetrics.textures,
      renderedBlocks: port.renderedBlocks,
      renderedDecorations: port.renderedDecorations,
      object3dCount: renderCost.object3dCount,
      meshCount: renderCost.meshCount,
      visibleMeshCount: renderCost.visibleMeshCount,
      instanceMeshCount: counters.instancedMeshCount,
      instanceMembers: counters.instancedMembers,
      renderRegionSize: port.renderRegionSize,
      renderRegionCount: renderCost.regions,
      regionalInstanceBatchCount: renderCost.instance.batchCount,
      regionalInstanceMeshCount: renderCost.instance.meshCount,
      regionalSurfaceBatchCount: renderCost.surface.batchCount,
      instanceMaterialCount: renderCost.instance.materials,
      instanceGeometryCount: renderCost.instance.geometries,
      staticModelCandidates: staticModelMetrics.candidates,
      staticModelBatchable: staticModelMetrics.batchable,
      staticModelBatchedMembers: staticModelMetrics.batchedMembers,
      staticModelTemplateCacheHits: staticModelMetrics.templateCacheHits,
      staticModelTemplateCacheMisses: staticModelMetrics.templateCacheMisses,
      providerObjectsAvoidedByStaticCache: staticModelMetrics.providerObjectsAvoidedByStaticCache,
      staticModelRejected: staticModelMetrics.rejected,
      staticModelBatchCount: port.instanceBatchCount,
      staticModelInstanceMeshCount: renderCost.instance.meshCount,
      fluidLogicalVoxels: port.fluidDiagnostics.fluidLogicalVoxels,
      fluidChunks: port.fluidDiagnostics.fluidChunks,
      fluidChunkMeshes: port.fluidDiagnostics.fluidChunkMeshes,
      fluidStandaloneMeshes: port.fluidDiagnostics.fluidStandaloneMeshes,
      fluidFacesPotential: port.fluidDiagnostics.fluidFacesPotential,
      fluidFacesCulled: port.fluidDiagnostics.fluidFacesCulled,
      fluidFacesEmitted: port.fluidDiagnostics.fluidFacesEmitted,
      fluidMaterialBuckets: port.fluidDiagnostics.fluidMaterialBuckets,
      standaloneBlockObjects: renderCost.standaloneBlockObjects,
      standaloneBlockMeshes: renderCost.standaloneBlockMeshes,
      standaloneTransparentMeshes: renderCost.standaloneTransparentMeshes,
      standaloneOpaqueMeshes: renderCost.standaloneOpaqueMeshes,
      placeholderBatches: renderCost.placeholders.batchCount,
      placeholderMeshes: renderCost.placeholders.meshCount,
      decorationObjects: renderCost.decorationObjects,
      decorationMeshes: renderCost.decorationMeshes,
      transparentMeshCount: renderCost.transparentMeshCount,
      opaqueMeshCount: renderCost.opaqueMeshCount,
      providerObjectCreations: counters.providerObjectCreations,
      reusableTemplateCreations: counters.reusableTemplateCreations,
      reusableTemplateCacheHits: counters.reusableTemplateCacheHits,
      rawInstanceTemplateParts: counters.rawInstanceTemplateParts,
      mergedInstanceTemplateParts: counters.mergedInstanceTemplateParts,
      templateMergeOperations: counters.templateMergeOperations,
      templatePartsEliminated: counters.templatePartsEliminated,
      instancedBoundsComputations: counters.instancedBoundsComputations,
      fallbackMeshCreations: counters.fallbackMeshCreations,
      cachedTemplateInsertions: counters.cachedTemplateInsertions,
      cameraMovementFrames: counters.cameraMovementFrames,
      cameraMovementRenderCalls: counters.cameraMovementRenderCalls,
      cameraChangeEventsDuringMovement: counters.cameraChangeEventsDuringMovement,
      cameraRenderRequestsSuppressed: counters.cameraRenderRequestsSuppressed,
      controlChangeEvents: counters.controlChangeEvents,
      cameraRenderRequests: counters.cameraRenderRequests,
      cameraRendersExecuted: counters.cameraRendersExecuted,
      cameraRenderRequestsCoalesced: counters.cameraRenderRequestsCoalesced,
      interactiveResolutionEntries: counters.interactiveResolutionEntries,
      staticResolutionRestores: counters.staticResolutionRestores,
      regularHydrationStarted: counters.regularHydrationStarted,
      regularHydrationCompleted: counters.regularHydrationCompleted,
      providerRefreshStarted: counters.providerRefreshStarted,
      providerRefreshCompleted: counters.providerRefreshCompleted,
      hydrationFairnessDeferrals: counters.hydrationFairnessDeferrals,
      maxProviderRefreshRunningWhileRegularPending: counters.maxProviderRefreshRunningWhileRegularPending,
      hydrationPausesForCamera: counters.hydrationPausesForCamera,
      hydrationJobsStartedWhileCamera: counters.hydrationJobsStartedWhileCamera,
      hydrationProgressRegressions: counters.hydrationProgressRegressions,
      cameraOnlyGenerationChanges: counters.cameraOnlyGenerationChanges,
      blockSignatureComputations: counters.blockSignatureComputations,
      hoverRaycasts: counters.hoverRaycasts,
      hoverRaycastsSuppressedDuringCamera: counters.hoverRaycastsSuppressedDuringCamera,
      hoverPointerMovesCoalesced: counters.hoverPointerMovesCoalesced,
      hydrationQueue: port.hydrationQueue,
      interiorBlocksCulled: port.interiorBlocksCulled,
      hydrationRunning: port.hydrationRunning,
      frameDurationMs: port.frameDurationMs,
      renderCpuMs: port.renderCpuMs,
      drawCalls: port.lastRendererMetrics.calls,
      lines: port.lastRendererMetrics.lines,
      points: port.lastRendererMetrics.points,
      instanceBatches: port.instanceBatchCount,
      instancedMeshCount: renderCost.instance.meshCount,
      nonInstancedMeshCount: Math.max(0, renderCost.meshCount - renderCost.instance.meshCount),
      renderableBlocks: port.renderedBlocks,
      surfaceFastPathBlocks: counters.surfaceFastPathBlocks,
      exposedFaceInstances: counters.exposedFaceInstances,
      neighborFacesCulled: counters.neighborFacesCulled,
      surfaceFaceBatches: port.surfaceFaceBatchCount,
      surfaceFaceInstancedMeshes: port.surfaceFaceBatchCount,
      hoverPickMs: counters.hoverPickMs,
      hoverPickCount: counters.hoverPickCount,
      hoverPickMaxMs: counters.hoverPickMaxMs,
      ddaPickCount: counters.ddaPickCount,
      ddaVisitedVoxels: counters.ddaVisitedVoxels,
      ddaFullCubeHits: counters.ddaFullCubeHits,
      precisePickFallbacks: counters.precisePickFallbacks,
      placementPreviewMs: counters.placementPreviewMs,
      placementPreviewCount: counters.placementPreviewCount,
      placementPreviewMaxMs: counters.placementPreviewMaxMs,
      placementPreviewFullProjectScans: counters.placementPreviewFullProjectScans,
      duplicatePlacementValidations: counters.duplicatePlacementValidations,
      spatialIndexBuilds: counters.spatialIndexBuilds,
      spatialIndexLookups: Math.max(counters.spatialIndexLookups, port.spatialIndexLookups),
      ghostVisualRebuilds: counters.ghostVisualRebuilds,
      ghostVisualReuses: counters.ghostVisualReuses,
      structuralReconciles: counters.structuralReconciles,
      overlayOnlyUpdates: counters.overlayOnlyUpdates,
      projectBoundsRebuilds: counters.projectBoundsRebuilds,
      fullProjectScansDuringHover: counters.fullProjectScansDuringHover,
      renderInvalidations: counters.renderInvalidations,
      renderInvalidationsCoalesced: counters.renderInvalidationsCoalesced,
      actualSceneRenders: counters.actualSceneRenders,
      terrainChunks: terrain.terrainChunks,
      terrainChunkMeshes: terrain.terrainChunkMeshes,
      terrainDrawObjectCount: terrain.terrainChunkMeshes,
      terrainTriangleCount: renderCost.terrainTriangleCount,
      terrainChunkRebuilds: terrain.terrainChunkRebuilds,
      terrainBlocksCompiled: terrain.terrainBlocksCompiled,
      terrainFacesEmitted: terrain.terrainFacesEmitted,
      terrainFacesCulled: terrain.terrainFacesCulled,
      terrainTemplateResolutions: terrain.terrainTemplateResolutions,
      terrainTemplateCacheHits: terrain.terrainTemplateCacheHits,
      terrainLogicalBlocks: terrain.terrainLogicalBlocks,
      terrainBulkBatches: terrain.terrainBulkBatches,
      terrainCandidateOwnershipTotal: terrain.terrainCandidateOwnershipTotal,
      terrainCandidateFanoutTotal: terrain.terrainCandidateFanoutTotal,
      maxHydrationCandidatesPerChunk: terrain.maxHydrationCandidatesPerChunk,
      maxRecordsPerChunk: terrain.maxRecordsPerChunk,
      terrainCommitCandidateChecks: terrain.terrainCommitCandidateChecks,
      terrainCommitRepresentedLookupChecks: terrain.terrainCommitRepresentedLookupChecks,
      terrainPendingHydrationCandidates: terrain.terrainPendingHydrationCandidates,
      terrainAsyncAcceptedResults: counters.terrainAsyncAcceptedResults,
      terrainAsyncStaleRevisionResults: counters.terrainAsyncStaleRevisionResults,
      terrainAsyncStaleGenerationResults: counters.terrainAsyncStaleGenerationResults,
      terrainAsyncStaleProviderResults: counters.terrainAsyncStaleProviderResults,
      terrainAsyncSupersededResults: counters.terrainAsyncSupersededResults,
      terrainAsyncRescheduledChunks: counters.terrainAsyncRescheduledChunks,
      terrainAsyncCommitPolicyRejected: counters.terrainAsyncCommitPolicyRejected,
      terrainAsyncAllUnrepresentedResults: counters.terrainAsyncAllUnrepresentedResults,
      terrainAsyncPartialFailureResults: counters.terrainAsyncPartialFailureResults,
      terrainAsyncWorkerFailures: counters.terrainAsyncWorkerFailures,
      terrainAsyncFallbackKeys: counters.terrainAsyncFallbackKeys,
      terrainAsyncRejectedWithoutReplacement: counters.terrainAsyncRejectedWithoutReplacement,
      terrainAtlasMode: port.terrainAtlasMode,
      terrainAtlasPages: terrain.terrainAtlas.terrainAtlasPages,
      terrainAtlasSprites: terrain.terrainAtlas.terrainAtlasSprites,
      terrainAtlasInsertions: terrain.terrainAtlas.terrainAtlasInsertions,
      terrainAtlasCacheHits: terrain.terrainAtlas.terrainAtlasCacheHits,
      terrainAtlasCompatibleFaces: terrain.terrainAtlas.terrainAtlasCompatibleFaces,
      terrainAtlasFallbackFaces: terrain.terrainAtlas.terrainAtlasFallbackFaces,
      terrainAtlasMaterials: terrain.terrainAtlas.terrainAtlasMaterials,
      terrainAtlasChunkBuckets: terrain.terrainAtlas.terrainAtlasChunkBuckets,
      terrainWorker: { ...terrain.terrainWorker, terrainWorkerCpuMs: { ...terrain.terrainWorker.terrainWorkerCpuMs }, terrainWorkerRoundTripMs: { ...terrain.terrainWorker.terrainWorkerRoundTripMs } },
      terrainCommit: { ...terrain.terrainCommit, terrainCommitCpuMs: { ...terrain.terrainCommit.terrainCommitCpuMs } },
    };
  }
